networks:
  n8naio:

x-n8n: &service-n8n
  image: n8nio/n8n:latest
  networks: ['n8naio']
  environment:
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=postgres
    - DB_POSTGRESDB_USER=${POSTGRES_USER}
    - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
    - N8N_DIAGNOSTICS_ENABLED=false
    - N8N_PERSONALIZATION_ENABLED=false
    - N8N_ENCRYPTION_KEY
    - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
    - N8N_USER_MANAGEMENT_JWT_SECRET
    - N8N_SECURE_COOKIE=false
  links:
    - postgres

x-mcpcheckpoint: &service-mcpcheckpoint
  image: ccastilloporras/chkp-mcp:001
  networks: ['n8naio']

x-ollama: &service-ollama
  image: ollama/ollama:latest
  container_name: ollama
  networks: ['n8naio']
  restart: unless-stopped
  environment:
    - OLLAMA_CONTEXT_LENGTH=8192
  volumes:
    - ollama_storage:/root/.ollama

x-init-ollama: &init-ollama
  image: ollama/ollama:latest
  networks: ['n8naio']
  container_name: ollama-pull-llama
  volumes:
    - ollama_storage:/root/.ollama
  entrypoint: /bin/sh
  command:
    - "-c"
    - "sleep 3; OLLAMA_HOST=ollama:11434 ollama pull deepseek-v3.1:671b-cloud; OLLAMA_HOST=ollama:11434 ollama pull qwen3-coder:480b-cloud; OLLAMA_HOST=ollama:11434 ollama pull nomic-embed-text:latest; OLLAMA_HOST=ollama:11434 ollama pull minimax-m2:cloud; OLLAMA_HOST=ollama:11434 ollama pull glm-4.6:cloud"

services:
  cgwafaio:
    profiles:
      - waf
    image: checkpoint/cloudguard-appsec-standalone:latest
    networks: ['n8naio']
    container_name: waf-aio
    ports:
      - 10.200.0.41:80:80
      - 10.200.0.41:443:443
      - 10.200.0.41:8117:8117
    volumes:
      - cgwaf_ssldata:/etc/certs/
      - cgwaf_logs:/var/log/nano_agent
    command: ["/cloudguard-appsec-standalone", "--token", "${CHECKPOINT_WAF_TOKEN}"]
    restart: always

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    networks: ['n8naio']
    restart: unless-stopped
    container_name: open-webui-aio
    ports:
      - 3006:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
    volumes:
      - open-webui:/app/backend/data

  postgres:
    image: postgres:16-alpine
    networks: ['n8naio']
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10
  
  n8n-import:
    profiles: ["import"]
    <<: *service-n8n
    container_name: n8n-import
    entrypoint: /bin/sh
    command:
      - "-c"
      - "n8n import:credentials --input=/backup/credentials/credential.json && n8n import:workflow --input=/backup/workflow/workflows.json"
    volumes:
      - ./n8n/backup:/backup
    depends_on:
      postgres:
        condition: service_healthy

  n8n-fresh:
    <<: *service-n8n
    profiles: ["new"]
    container_name: n8n-aio
    restart: unless-stopped
    ports:
      - 5680:5678
    volumes:
      - n8n_storage:/home/node/.n8n
      - ./n8nbackup/:/backup
      - ./chkpdocs:/data/shared #we save the pdf files here
    depends_on:
      postgres:
        condition: service_healthy

  n8n-imported:
    <<: *service-n8n
    profiles: ["import"]
    container_name: n8n-aio
    restart: unless-stopped
    ports:
      - 5680:5678
    volumes:
      - n8n_storage:/home/node/.n8n
      - ./n8nbackup/:/backup
      - ./chkpdocs:/data/shared #we save the pdf files here
    depends_on:
      postgres:
        condition: service_healthy
      n8n-import:
        condition: service_completed_successfully
  
  managementmcp:
    <<: *service-mcpcheckpoint
    container_name: managementmcpaio
    restart: unless-stopped
    environment:
      - MCP_SRV=quantum-management-mcp
      - API_KEY=${API_KEY_MGMT}
      - MANAGEMENT_HOST=${CHECKPOINT_HOST}

  reputationmcp:
    <<: *service-mcpcheckpoint
    container_name: reputationmcpaio
    restart: unless-stopped
    environment:
      - MCP_SRV=reputation-service-mcp
      - API_KEY=${API_KEY_REPUTATION}

## Run as many of this services as MCP needed
  #reputationmcp:
  #  <<: *service-mcpcheckpoint
  #  container_name: reputationmcpaio
  #  restart: unless-stopped
  #  environment:
  #    - MCP_SRV=<set the MCP from Check Point you want to call> use the name from the list of available servers https://github.com/CheckPointSW/mcp-servers
  #    - API_KEY=${API_KEY_REPUTATION}

  docsmcp:
    image: ccastilloporras/chkp-mcp-docs:001
    networks: ['n8naio']
    container_name: docsmcpaio
    restart: unless-stopped
    environment:
      - MCP_SRV=documentation-mcp
      - CLIENT_ID=${INF_PORTAL_ID}
      - SECRET_KEY=${INF_PORTAL_API}
      - REGION=${REGION}

  ollama-cpu:
    profiles: ["cpu"]
    <<: *service-ollama

  ollama-gpu:
    profiles: ["gpu-nvidia"]
    <<: *service-ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ollama-pull-llama-cpu:
    profiles: ["cpu"]
    <<: *init-ollama
    depends_on:
      - ollama-cpu

  ollama-pull-llama-gpu:
    profiles: ["gpu-nvidia"]
    <<: *init-ollama
    depends_on:
      - ollama-gpu
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - 6333:6333
    networks: ['n8naio']
    restart: unless-stopped
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  n8n_storage:
  postgres_storage:
  ollama_storage:
  qdrant_storage:
  open-webui:
  cgwaf_ssldata:
  cgwaf_logs:
